FROM daocloud.io/gizwits2015/docker-maven-tomcat:1.0.0
MAINTAINER Yan Liu <yliu@gizwits.com>

ENV CATALINA_HOME /usr/local/tomcat

ADD . /tmp/build/
RUN cd /tmp/build && mvn -e -DskipTests=true clean install \
    && rm -rf $CATALINA_HOME/webapps/* \
    && mv gizwits-lease-app/target/*.war $CATALINA_HOME/webapps/ROOT.war \
    && cd / && rm -rf /tmp/build

EXPOSE 8080
CMD ["catalina.sh", "run"]